; App::Mi6 config
name = SingleCheck
source-url = https://github.com/tbrowder/SingleCheck

[ReadmeFromPod]
filename = docs/Overview.rakudoc

[UploadToZef]

[Badges]
provider = github-actions/linux.yml
provider = github-actions/macos.yml
provider = github-actions/windows.yml

[RunAfterBuild]
; Generate Markdown from Rakudoc for GitHub reading
cmd = raku --doc=Markdown docs/Overview.rakudoc > README.md
cmd = raku --doc=Markdown docs/Usage.rakudoc > docs/Usage.md
cmd = raku --doc=Markdown docs/Config.rakudoc > docs/Config.md
